[2025-10-05 12:15:47,133 : INFO : main : Welcome to the custome log]
[2025-10-06 20:38:12,348 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-06 20:38:12,376 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-06 20:38:12,380 : INFO : common : created directory at: artifacts]
[2025-10-06 20:38:12,383 : INFO : common : created directory at: artifacts/data_ingestion]
[2025-10-06 20:47:25,916 : INFO : 992920486 : Downloaded data from https://drive.google.com/file/d/1nqErll4XHotgg8sLlXfXkHFHQ4fC69od/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-06 21:41:31,699 : INFO : main : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-06 21:41:31,702 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-06 21:41:31,704 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-06 21:41:31,705 : INFO : common : created directory at: artifacts]
[2025-10-06 21:41:31,707 : INFO : common : created directory at: artifacts/data_ingestion]
[2025-10-06 21:43:02,881 : ERROR : main : [Errno 28] No space left on device]
Traceback (most recent call last):
  File "C:\Users\Inshal Munaf\VsCodeProjects\Kidney_disease_Classification_MLOPS\main.py", line 10, in <module>
    obj.main()
  File "c:\users\inshal munaf\vscodeprojects\kidney_disease_classification_mlops\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\inshal munaf\vscodeprojects\kidney_disease_classification_mlops\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "c:\users\inshal munaf\vscodeprojects\kidney_disease_classification_mlops\src\cnnClassifier\components\data_ingestion.py", line 27, in download_file
    gdown.download(prefix+fileid , zip_download_dir)
  File "C:\Users\Inshal Munaf\AppData\Local\Programs\Python\Python311\Lib\site-packages\gdown\download.py", line 369, in download
    f.write(chunk)
OSError: [Errno 28] No space left on device
[2025-10-06 21:54:06,933 : INFO : main : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-06 21:54:06,933 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-06 21:54:06,933 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-06 21:54:06,933 : INFO : common : created directory at: artifacts]
[2025-10-06 21:54:06,933 : INFO : common : created directory at: artifacts/data_ingestion]
[2025-10-06 22:03:55,158 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1nqErll4XHotgg8sLlXfXkHFHQ4fC69od/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-06 22:04:18,312 : INFO : main : >>>>>> stage Data Ingestion Stage completed <<<<<< 

==========]
[2025-10-13 16:48:29,399 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-13 16:48:29,468 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-13 16:48:29,473 : INFO : common : created directory at: artifacts]
[2025-10-13 16:48:29,492 : INFO : common : created directory at: artifacts/prepare_base_model]
[2025-10-13 16:49:24,168 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-13 17:14:21,649 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-13 17:14:21,660 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-13 17:14:21,664 : INFO : common : created directory at: artifacts]
[2025-10-13 17:14:21,668 : INFO : common : created directory at: artifacts/prepare_base_model]
[2025-10-13 17:14:22,672 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-13 20:10:34,771 : INFO : main : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-13 20:10:34,797 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-13 20:10:34,818 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-13 20:10:34,820 : INFO : common : created directory at: artifacts]
[2025-10-13 20:10:34,821 : INFO : common : created directory at: artifacts/data_ingestion]
[2025-10-13 20:28:36,825 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1nqErll4XHotgg8sLlXfXkHFHQ4fC69od/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-13 20:28:57,607 : INFO : main : >>>>>> stage Data Ingestion Stage completed <<<<<< 

==========]
[2025-10-13 20:28:57,608 : INFO : main : >>>>>> stage Prepare Base Model started <<<<<<]
[2025-10-13 20:28:57,610 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-13 20:28:57,611 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-13 20:28:57,612 : INFO : common : created directory at: artifacts]
[2025-10-13 20:28:57,612 : INFO : common : created directory at: artifacts/prepare_base_model]
[2025-10-13 20:28:58,456 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-13 20:28:58,704 : INFO : main : >>>>>> stage Prepare Base Model completed <<<<<< 

==========]
[2025-10-20 15:58:50,909 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-20 15:58:50,926 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-20 15:58:50,929 : INFO : common : created directory at: artifacts]
[2025-10-20 15:58:50,934 : INFO : common : created directory at: artifacts/training]
[2025-10-20 15:59:22,925 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-20 15:59:22,935 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-20 15:59:22,940 : INFO : common : created directory at: artifacts]
[2025-10-20 15:59:22,943 : INFO : common : created directory at: artifacts/training]
[2025-10-20 18:30:00,684 : INFO : main : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-20 18:30:00,737 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-20 18:30:00,743 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-20 18:30:00,745 : INFO : common : created directory at: artifacts]
[2025-10-20 18:30:00,746 : INFO : common : created directory at: artifacts/data_ingestion]
[2025-10-20 19:30:52,054 : ERROR : main : ('Connection broken: IncompleteRead(1040328328 bytes read, 583112401 more expected)', IncompleteRead(1040328328 bytes read, 583112401 more expected))]
Traceback (most recent call last):
  File "C:\miniconda\envs\kidney\lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "C:\miniconda\envs\kidney\lib\site-packages\urllib3\response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(1040328328 bytes read, 583112401 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\miniconda\envs\kidney\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\miniconda\envs\kidney\lib\site-packages\urllib3\response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\miniconda\envs\kidney\lib\site-packages\urllib3\response.py", line 977, in read
    data = self._raw_read(amt)
  File "C:\miniconda\envs\kidney\lib\site-packages\urllib3\response.py", line 902, in _raw_read
    self._fp.close()
  File "C:\miniconda\envs\kidney\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\miniconda\envs\kidney\lib\site-packages\urllib3\response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(1040328328 bytes read, 583112401 more expected)', IncompleteRead(1040328328 bytes read, 583112401 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    obj.main()
  File "c:\users\inshal munaf\vscodeprojects\kidney_disease_classification_mlops\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\inshal munaf\vscodeprojects\kidney_disease_classification_mlops\src\cnnClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "c:\users\inshal munaf\vscodeprojects\kidney_disease_classification_mlops\src\cnnClassifier\components\data_ingestion.py", line 27, in download_file
    gdown.download(prefix+fileid , zip_download_dir)
  File "C:\miniconda\envs\kidney\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\miniconda\envs\kidney\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(1040328328 bytes read, 583112401 more expected)', IncompleteRead(1040328328 bytes read, 583112401 more expected))
[2025-10-21 18:19:34,993 : INFO : main : >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-10-21 18:19:35,007 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-21 18:19:35,020 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-21 18:19:35,022 : INFO : common : created directory at: artifacts]
[2025-10-21 18:19:35,022 : INFO : common : created directory at: artifacts/data_ingestion]
[2025-10-21 18:31:25,145 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1nqErll4XHotgg8sLlXfXkHFHQ4fC69od/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-10-21 18:31:46,710 : INFO : main : >>>>>> stage Data Ingestion Stage completed <<<<<< 

==========]
[2025-10-21 18:31:46,711 : INFO : main : >>>>>> stage Prepare Base Model started <<<<<<]
[2025-10-21 18:31:46,714 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-21 18:31:46,716 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-21 18:31:46,717 : INFO : common : created directory at: artifacts]
[2025-10-21 18:31:46,718 : INFO : common : created directory at: artifacts/prepare_base_model]
[2025-10-21 18:31:50,113 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-21 18:31:50,360 : INFO : main : >>>>>> stage Prepare Base Model completed <<<<<< 

==========]
[2025-10-21 18:31:50,361 : INFO : main : >>>>>> stage Prepare Base Model started <<<<<<]
[2025-10-21 18:31:50,364 : INFO : common : yaml file: config\config.yaml loaded successfully]
[2025-10-21 18:31:50,366 : INFO : common : yaml file: params.yaml loaded successfully]
[2025-10-21 18:31:50,367 : INFO : common : created directory at: artifacts]
[2025-10-21 18:31:50,368 : INFO : common : created directory at: artifacts/training]
[2025-10-21 19:15:46,425 : INFO : main : >>>>>> stage Prepare Base Model completed <<<<<< 

==========]
